### ISSUE TITLE
Revision de variables de control

### ISSUE THREAD

**Issue by napaza147** [napaza147/Quiz_1#3]
Son los códigos añadidos los más eficientes?...
https://github.com/napaza147/IE2/blob/e7e5703a631d7e98f0a8650f1acdc13b44a7bdc8/initial_quiz/models.py#L175-L185

**Comment by mgutierrezc** [comment]
Lo recomendable es crear cada grupo de `choices` en `Constants` y si necesitan usar alguno de esos grupos más de una vez, solo llaman a la misma constante cada vez que la necesiten:

En `Constants`, añadir algo como:
```python
choices_alfa = [[1, "a"], [2, "b"]]
```
