### ISSUE TITLE
Corregir estructura del repo 

### ISSUE THREAD

**Issue by mgutierrezc** [napaza147/Quiz_1#4]
Hola muchachos, 

El repo deberia ser igual a la carpeta de la aplicacion, por ej, deberia verse asi:

![image](https://user-images.githubusercontent.com/43623521/106064483-f2036800-60c7-11eb-9c03-55f02d381faa.png)

Esa estructura es necesaria para poder pullear al repo en el servudir

**Comment by napaza147** [comment]
Que tal, Marco.

Como usaremos varias aplicaciones, reestructuramos nuestros _branches_: colocamos el proyecto y las aplicaciones están dentro. Nos comentas, por favor, si es adecuado.

**Comment by napaza147** [comment]
Caso contrario, crearemos 3 repos nuevas y le mandaremos acceso cuanto antes.

**Comment by mgutierrezc** [comment]
Hola muchachos, 

Como el servidor del lab ya tiene un proyecto, sus repositorios deberian tener solo a las aplicaciones, tal como lo muestro en este comentario:

> Hola muchachos,
> 
> El repo deberia ser igual a la carpeta de la aplicacion, por ej, deberia verse asi:
> 
> ![image](https://user-images.githubusercontent.com/43623521/106064483-f2036800-60c7-11eb-9c03-55f02d381faa.png)
> 
> Esa estructura es necesaria para poder pullear al repo en el servudir

Si tienen problemas para setearlo de esa manera, podemos reunirnos antes de que hagan algun cambio

Por otro lado, gracias por avisarme sobre esto:

> Caso contrario, crearemos 3 repos nuevas y le mandaremos acceso cuanto antes.

Por favor, no eliminar nunca ningún repositorio sin mi supervisión. Si lo hacen, perderíamos el track de todos los cambios que se han hecho hasta ahora y de lo que queda pendiente por hacer. 

Tal vez debamos reunirnos estos días para conversar sobre sus repos. Me comentan porfa
