### ISSUE TITLE
Añadir .gitignore

### ISSUE THREAD

**Issue by mgutierrezc** [napaza147/Quiz_1#5]
Añadan un archivo sin nombre y con extension `.gitignore` despues de arreglar la estructura y en cada repo que contenga un app. Su contenido debe ser el sgte

```
__pycache__/
*.py[cod]
_builtin/

# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]

# C extensions
*.so

# Distribution / packaging
.Python
env/
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
*.egg-info/
.installed.cfg
*.egg

# PyInstaller
#  Usually these files are written by a python script from a template
#  before PyInstaller builds the exe, so as to inject date/other infos into it.
*.manifest
*.spec

# Installer logs
pip-log.txt
pip-delete-this-directory.txt

# Unit test / coverage reports
htmlcov/
.tox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*,cover

# Translations
*.mo
*.pot

# Django stuff:
*.log

# Sphinx documentation
docs/_build/

# PyBuilder
target/
```

Este es un archivo sin nombre con extensión ".gitignore":

https://stackoverflow.com/questions/10744305/how-to-create-a-gitignore-file

Sirve para evitar el trackeo de carpetas y archivos del repo. Las carpetas que les mencioné tienen archivos binarios (*.pyc) que causan conflictos con el servidor. Con el gitignore, se evita que se suban

Despues de añadirlo, borren `__pycache__` y `_builtin/__pycache__`. En el segundo caso, solo esa subcarpeta, no todo `_builtin`

**Comment by napaza147** [comment]
Hecho.

**Comment by mgutierrezc** [comment]
Veo que todavia no han añadido el archivo a su repo. Si tienen problemas para hacerlo, avisenme
