### ISSUE TITLE
Añadir etiqueta de participante en cada pagina

### ISSUE THREAD

**Issue by mgutierrezc** [napaza147/Quiz_1#6]
En el extremo superior derecho de cada página, debe aparecer la etiqueta de participante. Usen el siguiente formato

Pages:
```python 
    def vars_for_template(self):
        return dict(participant_id = self.participant.label)
```

Template:
```html
<font color="burlywood"><h4 align="right">Tu Etiqueta: {{ participant_id }}</h4></font>
```

**Comment by napaza147** [comment]
Hecho.

**Comment by mgutierrezc** [comment]
Un detalle más: si completan un issue, cierrenlo nomas. Cuando todos los issues estén cerrados, revisaré que se hayan hecho como corresponden. Si tienen dudas a la hora de solucionar uno, pueden comentar allí directamente con los problemas que presenten
